# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb2a9e98054eb1c2399940664de1a13140735274c7c04d51c73fa9b56459f7f50a79ce12a7dcdc509c46e18cbc882c05a3a85c7e585373859c533c851d62eb4

test:
  secret_key_base: 480273058d26ab1a9873941226867a1e4d1ca590271f0cd5c2c63da6c6765271a675845e8c8bd6af90b917014521f4a8b8a6aa7193b931b0ee7b9ac93d9cd60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
